name: Update Live CMS

on:
  pull_request:
    types:
      - closed

env:
  USERNAME: kyrellousgigis
  TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  update_remote_cms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

       - name: Clone Other Repository
        run: |
          git clone https://${{ env.USERNAME }}:${{ env.TOKEN }}@github.com/am-vodafone/cms-test cms-test

      - name: Update CMS
        run: |
          cp -R CMS/* cms-test/cms

      - name: Commit and Push Changes
        run: |
          cd cms-test
          git config user.name "GitHub Actions"
          git config user.email "kyrellous.girgis@vodafone.com"
          git add -A
          git commit -m "Update CMS"
         git push origin HEAD:refs/heads/update-cms
          hub pull-request -b am-vodafone:main -h kyrellousgirgis:update-cms -m "Update CMS"
          rm -rf cms-test
